# Generated by Django 4.1.7 on 2023-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
