# Generated by Django 4.1.4 on 2023-05-20 14:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
