# Generated by Django 4.1.4 on 2023-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tags',
            new_name='hashtags',
        ),
    ]
