# Generated by Django 4.1.4 on 2023-08-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_tags_blog_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='group',
            new_name='tags',
        ),
    ]
